apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2021-09-17T13:50:41Z"
  labels:
    kubernetes.io/metadata.name: nginx-demo
  name: nginx-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-demo
  name: nginx-demo
  namespace: nginx-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx-demo
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx-demo
    spec:
      containers:
        - image: nginx-demo
          name: nginx-demo
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always

---

apiVersion: v1
kind: Service

metadata:
  namespace: nginx-demo
  labels:
    io.kompose.service: nginx-demo
  name: nginx-demo
spec:
  type: NodePort
  ports:
    - name: "web"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: nginx-demo
status:
  loadBalancer: {}
